### ISSUE TITLE
Vanilla Customizer Not loading and crashing 

### ISSUE THREAD

**Issue by diaexa** [PluginBugs/Issues-VanillaCustomizer#16]
### Terms

- [X] I'm using the very latest version of VanillaCustomizer and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-VanillaCustomizer/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/vanillacustomizer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

exadia

### What happened?

Vanilla customizer is not loading into my server. I put it in made sure to have the correct and updated dependencies and started the server. However when i start it up it gives me an error and a warning then the server as a whole crashes and doesnt load. This loops until i stop the server and remove vanilla customizer. It also seems to break magic cosmetics as only when vanilla customizer is in the server breaks but once its removed the server is fine. This is with the latest version of itemsadder, magic cosmetics, protocol lib, lonelibs. on version 1.21 paper jar

### Steps to reproduce the issue

1. Put vanilla customizer in my server
2. start up the server
3. server errors and crashes and loops restart
4. remove vanilla customizer
5. no errors or loops server starts up normally
6. 

### Server version

Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### VanillaCustomizer Version

NA plugin wont even load

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.59

### FULL server log

[latest (1).log](https://github.com/user-attachments/files/17067499/latest.1.log)

### Error (optional)

```Shell
[22:18:43 ERROR]: [VanillaCustomizer] Error getting implementation for class dev.lone.vanillacustomizer.nms.items.ItemsNms - NMS v1_21
[22:18:43 WARN]: java.lang.ClassNotFoundException: dev.lone.vanillacustomizer.nms.items.impl.v1_21
[22:18:43 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[22:18:43 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[22:18:43 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[22:18:43 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:18:43 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[22:18:43 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[22:18:43 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[22:18:43 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[22:18:43 WARN]:        at VanillaCustomizer-0.3.jar//dev.lone.vanillacustomizer.nms.NMS.findImplementation(NMS.java:40)
[22:18:43 WARN]:        at VanillaCustomizer-0.3.jar//dev.lone.vanillacustomizer.nms.items.ItemsNms.<init>(ItemsNms.java:20)
[22:18:43 WARN]:        at VanillaCustomizer-0.3.jar//dev.lone.vanillacustomizer.nms.items.ItemsNms.inst(ItemsNms.java:26)
[22:18:43 WARN]:        at VanillaCustomizer-0.3.jar//dev.lone.vanillacustomizer.Main.onEnable(Main.java:52)
[22:18:43 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[22:18:43 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[22:18:43 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[22:18:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[22:18:43 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[22:18:43 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[22:18:43 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[22:18:43 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[22:18:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[22:18:43 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[22:18:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[22:18:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:18:43 INFO]: [VanillaCustomizer] Disabling VanillaCustomizer v0.3
[22:18:43 ERROR]: Error occurred while enabling VanillaCustomizer v0.3 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at VanillaCustomizer-0.3.jar/dev.lone.vanillacustomizer.Main.onEnable(Main.java:54) ~[VanillaCustomizer-0.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LoneDev6** [comment]
Update to 1.21.1 do not use 1.21, it's old and outdated.
